In [2]:
import keras
import json
import tensorflow as tf
import urllib
from io import StringIO
from PIL import Image
import numpy as np
import pandas as pd
import csv

Using TensorFlow backend.
/Users/hwiyoung_park/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [76]:
from keras.models import model_from_json

with open('model_architecture_modified.json', 'r') as f:
    model1 = model_from_json(f.read())
    model1.compile(optimizer='adadelta', metrics=['accuracy'], loss='crossentropy')

ValueError: Invalid objective: crossentropy

In [ ]:
GEOCODE_BASE_URL = "https://maps.googleapis.com/maps/api/geocode/json?address="

wb = pd.read_excel('DDW_PCA1024_2011_MDDS with UI.xlsx', sheet_name='Sheet1')
rows, cols = wb.shape

f1 = open('region_info_train.csv', 'w', encoding='utf-8', newline='')
#f2 = open('region_info_valid.csv', 'w', encoding='utf-8', newline='')
#f3 = open('region_info_test.csv', 'w', encoding='utf-8', newline='')
wr1 = csv.writer(f1)
#wr2 = csv.writer(f2)
#wr3 = csv.writer(f3)
wr1.writerow(['village_code', 'village_name', 'district_code', 'subdistrict_code', 'num_households', 'centre_lat', 'centre_lng'])
#wr2.writerow(['village_code', 'village_name', 'subdistrict_code', 'num_households', 'centre_lat', 'centre_lng'])
#wr3.writerow(['village_code', 'village_name', 'subdistrict_code', 'num_households', 'centre_lat', 'centre_lng'])

check = 0

for r in range(rows):
    if r * 100 / rows >= check:
        print(check, "% done!")
        check += 1
        
    #if wb.iloc[r, 3] != 0 and wb.iloc[r, 4] == 0 and wb.iloc[r, 9] >= 100"""and r < rows*0.8""":
    if wb.iloc[r, 3] != 0 and wb.iloc[r, 4] == 0 and wb.iloc[r, 9] >= 100:
        #print(wb.iloc[r, 3], wb.iloc[r, 7])
        
        url = GEOCODE_BASE_URL + wb.iloc[r, 7].replace(" ", "+") + "&components=country:IN&key=AIzaSyAg5p0OR-RG5an0GzzhhcoRD-FD7bDOcz4"
        response = simplejson.load(urllib.request.urlopen(url))
        if len(response['results']) != 0:
            lat = response['results'][0]['geometry']['location']['lat']
            lng = response['results'][0]['geometry']['location']['lng']
        
            wr1.writerow([wb.iloc[r, 3], wb.iloc[r, 7], wb.iloc[r, 1], wb.iloc[r, 2], wb.iloc[r, 9], round(lat, 7), round(lng, 7)])
    """    
    elif wb.iloc[r, 3] != 0 and wb.iloc[r, 4] == 0 and wb.iloc[r, 9] >= 100 and r < rows*0.9:
        #print(wb.iloc[r, 3], wb.iloc[r, 7])
        
        url = GEOCODE_BASE_URL + wb.iloc[r, 7].replace(" ", "+") + "&components=country:IN&key=AIzaSyAg5p0OR-RG5an0GzzhhcoRD-FD7bDOcz4"
        response = simplejson.load(urllib.request.urlopen(url))
        if len(response['results']) != 0:
            lat = response['results'][0]['geometry']['location']['lat']
            lng = response['results'][0]['geometry']['location']['lng']
        
            wr2.writerow([wb.iloc[r, 3], wb.iloc[r, 7], wb.iloc[r, 2], wb.iloc[r, 9], round(lat, 7), round(lng, 7)])
        
    elif wb.iloc[r, 3] != 0 and wb.iloc[r, 4] == 0 and wb.iloc[r, 9] >= 100:
        #print(wb.iloc[r, 3], wb.iloc[r, 7])
        
        url = GEOCODE_BASE_URL + wb.iloc[r, 7].replace(" ", "+") + "&components=country:IN&key=AIzaSyAg5p0OR-RG5an0GzzhhcoRD-FD7bDOcz4"
        response = simplejson.load(urllib.request.urlopen(url))
        if len(response['results']) != 0:
            lat = response['results'][0]['geometry']['location']['lat']
            lng = response['results'][0]['geometry']['location']['lng']
        
            wr3.writerow([wb.iloc[r, 3], wb.iloc[r, 7], wb.iloc[r, 2], wb.iloc[r, 9], round(lat, 7), round(lng, 7)])
   """     
f1.close()
#f2.close()
#f3.close()

In [62]:
wb = pd.read_excel('HLPCA-10226-2011_H14_census.xlsx', sheet_name='Sheet1')
rows, cols = wb.shape

f1 = open('region_info_train_y.csv', 'w', encoding='utf-8', newline='')
wr1 = csv.writer(f1)
wr1.writerow(['village_code', '0_0', '0_1', '0_2', '0_3', '0_4', '0_5', '0_6', '0_7', '0_8', '1_0', '1_1', '1_2', '1_3', '1_4', '1_5', '2_0', '2_1', '2_2', '2_3', '2_4', '2_5', '2_6', '2_7', '2_8', '2_9'])

check = 0
for r in range(rows):
    if r * 100 / rows >= check:
        print(check, "% done!")
        check += 1
        
    if wb.iloc[r, 6] != '000000' and wb.iloc[r, 7] == '0000':
        wr1.writerow([int(wb.iloc[r, 6]), round(wb.iloc[r, 22]/100, 3), round(wb.iloc[r, 23]/100, 3), round(wb.iloc[r, 24]/100, 3), round(wb.iloc[r, 25]/100, 3), round(wb.iloc[r, 26]/100, 3), round(wb.iloc[r, 27]/100, 3), round(wb.iloc[r, 28]/100, 3), round(wb.iloc[r, 29]/100, 3), round(wb.iloc[r, 30]/100, 3), round(wb.iloc[r, 84]/100, 3), round(wb.iloc[r, 85]/100, 3), round(wb.iloc[r, 86]/100, 3), round(wb.iloc[r, 87]/100, 3), round(wb.iloc[r, 88]/100, 3), round(wb.iloc[r, 89]/100, 3), round(wb.iloc[r, 71]/100, 3), round(wb.iloc[r, 72]/100, 3), round(wb.iloc[r, 73]/100, 3), round(wb.iloc[r, 74]/100, 3), round(wb.iloc[r, 75]/100, 3), round(wb.iloc[r, 76]/100, 3), round(wb.iloc[r, 77]/100, 3), round(wb.iloc[r, 78]/100, 3), round(wb.iloc[r, 79]/100, 3), round(wb.iloc[r, 80]/100, 3)])
        
f1.close()

0 % done!
1 % done!
2 % done!
3 % done!
4 % done!
5 % done!
6 % done!
7 % done!
8 % done!
9 % done!
10 % done!
11 % done!
12 % done!
13 % done!
14 % done!
15 % done!
16 % done!
17 % done!
18 % done!
19 % done!
20 % done!
21 % done!
22 % done!
23 % done!
24 % done!
25 % done!
26 % done!
27 % done!
28 % done!
29 % done!
30 % done!
31 % done!
32 % done!
33 % done!
34 % done!
35 % done!
36 % done!
37 % done!
38 % done!
39 % done!
40 % done!
41 % done!
42 % done!
43 % done!
44 % done!
45 % done!
46 % done!
47 % done!
48 % done!
49 % done!
50 % done!
51 % done!
52 % done!
53 % done!
54 % done!
55 % done!
56 % done!
57 % done!
58 % done!
59 % done!
60 % done!
61 % done!
62 % done!
63 % done!
64 % done!
65 % done!
66 % done!
67 % done!
68 % done!
69 % done!
70 % done!
71 % done!
72 % done!
73 % done!
74 % done!
75 % done!
76 % done!
77 % done!
78 % done!
79 % done!
80 % done!
81 % done!
82 % done!
83 % done!
84 % done!
85 % done!
86 % done!
87 % done!
88 % done!
89 % done!
90 % done!
91 % done

In [64]:
LOCCODE_BASE_URL = "https://maps.googleapis.com/maps/api/staticmap?center="

f1 = pd.read_csv('region_info_train.csv')
f2 = pd.read_csv('region_info_train_y.csv')
"""
url = LOCCODE_BASE_URL + str(f1.iloc[0, 5]) + "," + str(f1.iloc[0, 6]) + "&zoom=16&size=1920x1920&maptype=satellite&key=AIzaSyAg5p0OR-RG5an0GzzhhcoRD-FD7bDOcz4"
img = Image.open(urllib.request.urlopen(url)).convert("RGB")
img.show()

#village_code = 242473
#temp = np.array(f2[(f2.village_code == village_code)])
#print(temp[0, 1:])
"""
rows, cols = f1.shape

batch_size = 10

for i in range(rows//10):
    print("Current : ", i+1, "/", rows//10)
    count = 0
    if (i+1)*10 > rows:
        X = np.zeros(((i+1)*10 - rows, 640, 640, 3))
        y = np.zeros(((i+1)*10 - rows, 25))
        for j in range(i*10, rows):
            url = LOCCODE_BASE_URL + str(f1.iloc[j, 5]) + "," + str(f1.iloc[j, 6]) + "&zoom=16&size=1920x1920&maptype=satellite&key=AIzaSyAg5p0OR-RG5an0GzzhhcoRD-FD7bDOcz4"
            img = Image.open(urllib.request.urlopen(url)).convert("RGB")
            img = np.array(img)
            X[count, :, :, :] = img
            
            village_code = f1.iloc[j, 0]
            y[count, :] = np.array(f2[(f2.village_code == village_code)])[0, 1:]
            
            count += 1
            
    else:
        X = np.zeros((batch_size, 640, 640, 3))
        y = np.zeros((batch_size, 25))
        for j in range(i*10, (i+1)*10):
            url = LOCCODE_BASE_URL + str(f1.iloc[j, 5]) + "," + str(f1.iloc[j, 6]) + "&zoom=16&size=1920x1920&maptype=satellite&key=AIzaSyAg5p0OR-RG5an0GzzhhcoRD-FD7bDOcz4"
            img = Image.open(urllib.request.urlopen(url)).convert("RGB")
            img = np.array(img)
            X[count, :, :, :] = img
            
            village_code = f1.iloc[j, 0]
            y[count, :] = np.array(f2[(f2.village_code == village_code)])[0, 1:]
            
            count += 1

    model1.train_on_batch(X, [y[:, 0:9], y[:, 9:15], y[:, 15:]])


Current :  1 / 39
Current :  2 / 39
Current :  3 / 39
Current :  4 / 39
Current :  5 / 39
Current :  6 / 39
Current :  7 / 39
Current :  8 / 39
Current :  9 / 39
Current :  10 / 39
Current :  11 / 39
Current :  12 / 39
Current :  13 / 39
Current :  14 / 39
Current :  15 / 39
Current :  16 / 39
Current :  17 / 39
Current :  18 / 39
Current :  19 / 39
Current :  20 / 39
Current :  21 / 39
Current :  22 / 39
Current :  23 / 39
Current :  24 / 39
Current :  25 / 39
Current :  26 / 39
Current :  27 / 39
Current :  28 / 39
Current :  29 / 39
Current :  30 / 39
Current :  31 / 39
Current :  32 / 39
Current :  33 / 39
Current :  34 / 39
Current :  35 / 39
Current :  36 / 39
Current :  37 / 39
Current :  38 / 39
Current :  39 / 39


In [65]:
url = LOCCODE_BASE_URL + str(f1.iloc[0, 5]) + "," + str(f1.iloc[0, 6]) + "&zoom=16&size=1920x1920&maptype=satellite&key=AIzaSyAg5p0OR-RG5an0GzzhhcoRD-FD7bDOcz4"
img = Image.open(urllib.request.urlopen(url)).convert("RGB")
img = np.array(img)
X_test = img.reshape(1, 640, 640, 3)

village_code = f1.iloc[0, 0]
y_test = np.array(f2[(f2.village_code == village_code)])[0, 1:]
#model1.test_on_batch(X_test, [y_test[0:9].reshape(1, 9), y_test[9:15].reshape(1, 6), y_test[15:].reshape(1, 10)])
model1.predict_on_batch(X_test)

[array([[2.6361498e-03, 2.2046155e-05, 8.5435779e-05, 1.7676927e-02,
         3.4429564e-04, 3.1025970e-01, 6.6389704e-01, 1.9144827e-05,
         5.0592287e-03]], dtype=float32),
 array([[1.9839518e-02, 1.3054203e-09, 8.5810706e-02, 4.3386254e-02,
         8.4195328e-01, 9.0102386e-03]], dtype=float32),
 array([[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]], dtype=float32)]

In [75]:
LOCCODE_BASE_URL = "https://maps.googleapis.com/maps/api/staticmap?center="

f1 = pd.read_csv('region_info_train.csv')
f2 = pd.read_csv('region_info_train_y.csv')

url = LOCCODE_BASE_URL + str(f1.iloc[3, 5]) + "," + str(f1.iloc[3, 6]) + "&zoom=16&size=1920x1920&maptype=satellite&key=AIzaSyAg5p0OR-RG5an0GzzhhcoRD-FD7bDOcz4"
img = Image.open(urllib.request.urlopen(url)).convert("RGB")
img = np.array(img)
X_train = img.reshape(1, 640, 640, 3)

village_code = f1.iloc[3, 0]
y_train = np.array(f2[(f2.village_code == village_code)])[0, 1:]

for i in range(1000):
    if i % 10 == 0:
        print(i//10, "% done")
        
    model1.train_on_batch(X_train, [y_train[0:9].reshape(1, -1), y_train[9:15].reshape(1, -1), y_train[15:].reshape(1, -1)])

model1.predict_on_batch(X_train)

0 % done
1 % done
2 % done
3 % done
4 % done
5 % done
6 % done
7 % done
8 % done
9 % done
10 % done
11 % done
12 % done
13 % done
14 % done
15 % done
16 % done
17 % done
18 % done
19 % done
20 % done
21 % done
22 % done
23 % done
24 % done
25 % done
26 % done
27 % done
28 % done
29 % done
30 % done
31 % done
32 % done
33 % done
34 % done
35 % done
36 % done
37 % done
38 % done
39 % done
40 % done
41 % done
42 % done
43 % done
44 % done
45 % done
46 % done
47 % done
48 % done
49 % done
50 % done
51 % done
52 % done
53 % done
54 % done
55 % done
56 % done
57 % done
58 % done
59 % done
60 % done
61 % done
62 % done
63 % done
64 % done
65 % done
66 % done
67 % done
68 % done
69 % done
70 % done
71 % done
72 % done
73 % done
74 % done
75 % done
76 % done
77 % done
78 % done
79 % done
80 % done
81 % done
82 % done
83 % done
84 % done
85 % done
86 % done
87 % done
88 % done
89 % done
90 % done
91 % done
92 % done
93 % done
94 % done
95 % done
96 % done
97 % done
98 % done
99 % done


[array([[0.11081306, 0.11081306, 0.11114381, 0.11081306, 0.11267308,
         0.11115429, 0.11081306, 0.11081306, 0.11096352]], dtype=float32),
 array([[0.16535014, 0.16535014, 0.16535014, 0.16768906, 0.16535014,
         0.17091034]], dtype=float32),
 array([[0.09932344, 0.09932344, 0.09932344, 0.09932344, 0.10038717,
         0.09932344, 0.10255377, 0.09932344, 0.10147534, 0.0996431 ]],
       dtype=float32)]